# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: 考勤api打包 

on: 
  workflow_dispatch: 

jobs:
  develop_build:
    runs-on: windows-latest
    steps:
      - name: 考勤api打包 
        uses: actions/checkout@v3
      - name: 设置jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: 项目打包
        run: mvn -B package
